[package]
name = "acolor"
description = "Simple color types, operations and conversions."
version = "0.0.2"
edition = "2021"
resolver = "2"
rust-version = "1.64.0"
authors = ["José Luis Cruz <joseluis@andamira.net>"]
repository = "https://github.com/andamira/acolor"
documentation = "https://docs.rs/acolor"
license = "MIT OR Apache-2.0"
include = [
	"/src/**/*.rs",
	"/Cargo.toml",
	"/res/*",
	"/README.md",
	"/LICENSE-*",
]
categories = ["graphics", "no-std"]
keywords = ["color", "rgb", "lab"]
publish = true

[dependencies]
devela = { version = "0.1.2", default-features = false }
iunorm = "0.2.1"

approx = { version = "0.5.1", optional = true, default-features = false }
libm = { version = "0.2.5", optional = true }

macroquad = { version = "0.3.25", optional = true, default-features = false }
notcurses = { version = "3.1.0", optional = true }
sdl2 = { version = "0.35.2", optional = true, default-features = false, features = ["gfx"] }
tiny-skia = { version = "0.8.3", optional = true, default-features = false }

[features]
default = ["std", "safe", "approx"]
nightly = []

safe = ["devela/safe"]

std = ["devela/std", "tiny-skia?/std", "approx?/std"]
# --no-default-features --features=no-std
no-std = ["libm", "approx", "tiny-skia?/no-std-float"]

complete = ["macroquad", "notcurses", "sdl2", "tiny-skia"]

[dev-dependencies]

[package.metadata.docs.rs]
features = ["complete", "nightly"]

[badges]
maintenance = { status = "experimental" }
