[package]
name = "acolor"
description = "simple color types, operations and conversions"
version = "0.0.1"
edition = "2021"
resolver = "2"
rust-version = "1.64.0"
authors = ["José Luis Cruz <joseluis@andamira.net>"]
repository = "https://github.com/andamira/acolor"
documentation = "https://docs.rs/acolor"
license = "MIT OR Apache-2.0"
include = [
	"/src/**/*.rs",
	"/Cargo.toml",
	"/res/*",
	"/README.md",
	"/LICENSE-*",
]
categories = []
keywords = []
publish = false

[dependencies]
iunorm = "0.1.2"

# optional direct conversions

macroquad = { version = "0.3.24", optional = true, default-features = false }
notcurses = { version = "3.1.0", optional = true, default-features = false }
sdl2 = { version = "0.35.2", optional = true, default-features = false, features = ["gfx"] }
tiny-skia = { version = "0.8.1", optional = true, default-features = false }

[features]
default = ["std"]
std = ["tiny-skia?/std"]

all = ["macroquad", "notcurses", "sdl2", "tiny-skia"]

[dev-dependencies]

[package.metadata.docs.rs]
features = ["all"]

[badges]
# actively-developed, passively-maintained, looking-for-maintainer, as-is,
# experimental, deprecated, none
maintenance = { status = "experimental" }
