[alias]

# CHECK
cl = "clippy"
cl_all = "clippy --features=complete"

# CLEAN PACKAGE
cp = "clean --package"
crp = "clean --release --package"

# DOC
d = "doc --no-deps"
do = "doc --no-deps --open"
dd = "doc"
ddo = "doc --open"
# +nightly
nd = "doc --no-deps --features=nightly,complete"
ndo = "doc --no-deps --open --features=nighty,complete"
ndd = "doc --features=nightly,complete"
nddo = "doc --open --features=nightly,complete"

# BUILD
b = "build"
bb = "build --bin"
be = "build --example"
br = "build --release"
brb = "build --release --bin"
bre = "build --release --example"

# RUN
r = "run"
rb = "run --bin"
re = "run --example"
rr = "run --release"
rrb = "run --release --bin"
rre = "run --release --example"

# TEST
t = "test"
n_all = "test --features=nightly,complete"
td = "test --doc"
td_all = "test --doc --features=nightly,complete"
t_ = "test -- --nocapture"
t_1 = "test -- --test-threads 1 --nocapture"

# TREE
tr = "tree"
trf = "tree --format {p}:{f}" # with feature list
trr = "tree --format {p}:{r}" # with repository url

# PUBLISH
p = "publish --dry-run"
pa = "publish --dry-run --allow-dirty"
pp = "publish"
ppa = "publish --allow-dirty"

# Cargo subcommands:
## cargo-expand
E = "expand"
Eb = "expand --bin"
Ee = "expand --example"
El = "expand --lib"

[build]
